name: Ngrok CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # Build and package your application here
          echo "Building and packaging..."

      - name: Install Ngrok CLI
        run: |
          curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/

      - name: Start Ngrok tunnel
        run: |
          ngrok http 8080 &
          echo "Ngrok tunnel started"

      - name: Deploy to Ngrok
        run: |
          # Deploy your application here
          echo "Deploying to Ngrok..."
